configfile: "config/config.yaml"
import pandas as pd
import ast
from pathlib import Path
transcriptome = config['transcriptome']
transcriptome_name = Path(transcriptome).stem
output_folder = Path(config['output_folder']) / f"{config['experiment_id']}_vs_{transcriptome_name}"
index = Path(config['output_folder']) / "salmon_indices" / f"{transcriptome_name}_index"
samples_csv = config['samples']
fastqs_dir = Path(samples_csv).parent

df = pd.read_csv(samples_csv)
RUNS = df['Run'].tolist()

comparisons = config['comparisons']

rule all:
	input: 
		copied_config = output_folder / "config.yaml",
		gene_summary = output_folder / "significant_change_summaries" / "full_summary.csv",
		filtered_gene_summary = output_folder / "significant_change_summaries" / "filtered_summary.csv"
		

rule create_index:
	input: transcriptome = transcriptome
	output: index = directory(index)
	threads: 12
	shell:
		"salmon index -t {input.transcriptome} -i {output.index} -p {threads}"

rule quantify_with_salmon:
	input: 
		index = index,
		run_1 = fastqs_dir / "{current_run}_1.fastq.gz",
		run_2 = fastqs_dir / "{current_run}_2.fastq.gz"
	output: quant = directory(output_folder / "salmon_quants" / "{current_run}")
	threads: 8
	shell:
		'''
			salmon quant -i {input.index} \
			-l A \
			-1 {input.run_1} \
			-2 {input.run_2} \
			-p {threads} \
			--validateMappings \
			--gcBias \
			-o "{output.quant}"
		'''

rule run_deseq2:
	input:
		quantified_runs = expand(output_folder / "salmon_quants" / "{current_run}", current_run = RUNS),
		tx2gene = config['tx2gene'],
		samples_csv = samples_csv
	output:
		difex = output_folder / "deseq_output" / f"{{comparison}}_deseq.csv"
	params:
		output_folder = output_folder,
		RUNS = RUNS,
		comparison = lambda wildcards: wildcards.comparison,
		reference = lambda wildcards: wildcards.comparison.split('_')[-1]
	script:
		"scripts/run_deseq2.R"

rule summarize_genes_of_interest:
	input:
		difex = expand(output_folder / "deseq_output" / f"{{comparison}}_deseq.csv", comparison = comparisons),
	output:
		gene_summary = output_folder / "significant_change_summaries" / "full_summary.csv",
		filtered_gene_summary = output_folder / "significant_change_summaries" / "filtered_summary.csv"
	params:
		genes_of_interest = config['genes_or_te_of_interest'],
		p_val = config['p-value_cutoff']
	script:
		"scripts/summarize_te.py"

rule copy_config:
	output:
		copied_config = output_folder / "config.yaml"
	shell:
		"cp -f config/config.yaml {output.copied_config}"
