configfile: "config/config.yaml"
import pandas as pd
import ast
from pathlib import Path
transcriptome = config['transcriptome']
transcriptome_name = Path(transcriptome).stem
output_folder = Path(config['output_folder']) / f"{config['experiment_id']}_vs_{transcriptome_name}"
index = Path(config['output_folder']) / "salmon_indices" / f"{transcriptome_name}_index"
samples_csv = config['samples']
fastqs_dir = Path(samples_csv).parent
combined_summary = Path(config['output_folder']) / "combined_significant_change_summaries.csv"
filtered_combined_summary = Path(config['output_folder']) / "combined_significant_change_summaries_filtered.csv"
combined_summary.unlink(missing_ok=True)
filtered_combined_summary.unlink(missing_ok=True)

df = pd.read_csv(samples_csv)
RUNS = df['Run'].tolist()

comparisons = config['comparisons']

rule all:
	input: 
		copied_config = directory(output_folder / "config"),
		copied_workflow = directory(output_folder / "workflow"),
		combined_summary = combined_summary,
		filtered_combined_summary = filtered_combined_summary

rule create_index:
	input: transcriptome = transcriptome
	output: index = directory(index)
	threads: 12
	shell:
		"salmon index -t {input.transcriptome} -i {output.index} -p {threads}"

rule quantify_with_salmon:
	input: 
		index = index,
		run_1 = fastqs_dir / "{current_run}_1.fastq.gz",
		run_2 = fastqs_dir / "{current_run}_2.fastq.gz"
	output: quant = directory(output_folder / "salmon_quants" / "{current_run}")
	threads: 8
	shell:
		'''
			salmon quant -i {input.index} \
			-l A \
			-1 {input.run_1} \
			-2 {input.run_2} \
			-p {threads} \
			--validateMappings \
			--gcBias \
			-o "{output.quant}"
		'''

rule run_deseq2:
	input:
		quantified_runs = expand(output_folder / "salmon_quants" / "{current_run}", current_run = RUNS),
		tx2gene = config['tx2gene'],
		samples_csv = samples_csv
	output:
		difex = output_folder / "deseq_output" / f"{{comparison}}_deseq.csv"
	params:
		output_folder = output_folder,
		RUNS = RUNS,
		comparison = lambda wildcards: wildcards.comparison,
		reference = lambda wildcards: wildcards.comparison.split('_')[-1]
	script:
		"scripts/run_deseq2.R"

rule summarize_genes_of_interest:
	input:
		difex = expand(output_folder / "deseq_output" / f"{{comparison}}_deseq.csv", comparison = comparisons),
	output:
		gene_summary = output_folder / "significant_change_summary.csv",
	params:
		genes_of_interest = config['genes_or_te_of_interest'],
		p_val = config['p-value_cutoff']
	script:
		"scripts/summarize_te.py"

rule combine_summaries:
	input:
		gene_summary = output_folder / "significant_change_summary.csv",
	output:
		combined_summary = combined_summary,
		filtered_combined_summary = filtered_combined_summary
	run:
		summaries = []
		for path in Path('.').rglob('significant_change_summary.csv'):
			summaries.append(pd.read_csv(path, index_col=0))
		combined_summary = pd.concat(summaries)
		filtered_combined_summary = combined_summary[combined_summary.index.isin(config['genes_or_te_of_interest'])]
		combined_summary.to_csv(output.combined_summary, index=True)
		filtered_combined_summary.to_csv(output.filtered_combined_summary, index=True)

rule copy_config:
	output:
		copied_config = directory(output_folder / "config"),
		copied_workflow = directory(output_folder / "workflow")
	shell:
		"rsync -a config/ {output.copied_config} && rsync -a workflow/ {output.copied_workflow}"
