name: differential_expression
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - salmon
  - bioconductor-deseq2
  - bioconductor-tximport
  - bioconductor-tximportdata
  - bioconductor-apeglm
  - r-readr
  - r-yaml
  - snakemake
  - pandas
